version: "3.9"
services:
  web:
    image: roger21gm/gos-front
    stdin_open: true
    ports:
      - "80:80"
    networks:
      - gos-net
  server:
    image: roger21gm/gos-server
    ports:
      - "9090:9090"
    networks:
      - gos-net

networks:
  gos-net:
